import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      
      <main className="flex-1 container py-8">
        <Card className="max-w-4xl mx-auto">
          <CardHeader>
            <CardTitle>Disclaimer</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm max-w-none">
            <p><strong>Last updated:</strong> {new Date().toLocaleDateString()}</p>
            
            <h2>No Investment Advice</h2>
            <p>
              Meta Prompt Maker is a tool for improving prompt quality and does not provide 
              investment advice, recommendations, or guidance. Nothing on this platform should 
              be construed as investment advice or a recommendation to buy, sell, or hold any 
              securities or investments.
            </p>

            <h2>AI-Generated Content</h2>
            <p>
              All outputs from this platform are generated by artificial intelligence models. 
              These outputs:
            </p>
            <ul>
              <li>May contain errors, inaccuracies, or outdated information</li>
              <li>Should not be used as the sole basis for decision-making</li>
              <li>Require human review and verification before use</li>
              <li>May reflect biases present in training data</li>
            </ul>

            <h2>Professional Responsibility</h2>
            <p>
              Users are solely responsible for:
            </p>
            <ul>
              <li>Reviewing and verifying all AI-generated content</li>
              <li>Ensuring compliance with applicable laws and regulations</li>
              <li>Meeting professional and fiduciary duties</li>
              <li>Making independent investment and business decisions</li>
            </ul>

            <h2>Limitation of Liability</h2>
            <p>
              Altitude Global Advisors and Meta Prompt Maker shall not be liable for any 
              damages arising from the use of this platform, including but not limited to:
            </p>
            <ul>
              <li>Investment losses or missed opportunities</li>
              <li>Errors in AI-generated content</li>
              <li>System downtime or technical issues</li>
              <li>Regulatory compliance failures</li>
            </ul>

            <h2>Regulatory Compliance</h2>
            <p>
              Users in regulated industries (including financial services) are responsible 
              for ensuring their use of AI-generated content complies with all applicable 
              regulations, including but not limited to SEC, FINRA, and MiFID II requirements.
            </p>

            <h2>No Warranty</h2>
            <p>
              This platform is provided "as is" without warranties of any kind. We make no 
              guarantees regarding accuracy, completeness, or fitness for any particular purpose.
            </p>

            <h2>Changes to This Disclaimer</h2>
            <p>
              We reserve the right to update this disclaimer at any time. Continued use of 
              the platform constitutes acceptance of any changes.
            </p>
          </CardContent>
        </Card>
      </main>
      
      <Footer />
    </div>
  );
}
